[package]
name = "llamacpp_agent"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[features]
cuda = ["autoagents-llamacpp/cuda"]
cuda-no-vmm = ["autoagents-llamacpp/cuda-no-vmm"]
metal = ["autoagents-llamacpp/metal"]
vulkan = ["autoagents-llamacpp/vulkan"]

[dependencies]
autoagents = { workspace = true, features = ["logging"] }
autoagents-derive = { workspace = true }
autoagents-llamacpp = { workspace = true }
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
tokio-stream.workspace = true
