[package]
name = "vector-store-qdrant"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
autoagents-core = { workspace = true }
autoagents-llm = { workspace = true, features = ["openai"] }
autoagents-qdrant = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
