[package]
name = "vector-store-in-memory"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
autoagents-core = { workspace = true }
autoagents-llm = { workspace = true, features = ["openai"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
