[package]
name = "tts-agent-example"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
autoagents-core = { workspace = true, features = ["tts"] }
autoagents-tts = { workspace = true }
autoagents-pocket-tts = { workspace = true }
tokio = { workspace = true }
hound = { workspace = true}
env_logger = { workspace = true }
